services:
  - type: web
    name: wcu-check-app
    env: python
    plan: pro
    buildCommand: |
      chmod +x install.sh
      ./install.sh
    startCommand: gunicorn wcu_check.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wcu-check-db  # <-- Bunu öz Render Postgres servis adınla dəyiş
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: wcu_check.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10  # Ən stabil TensorFlow + dlib uyğundur
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - install.sh
        - render.yaml
