services:
  - type: web
    name: wcu-check
    env: python
    plan: pro-plus  # 8GB RAM
    buildCommand: |
      chmod +x install.sh
      ./install.sh
    startCommand: gunicorn wcu_check.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wcu-check-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: wcu_check.settings
      - key: SECRET_KEY
        generateValue: true
    buildFilter:
      paths:
        - requirements.txt
        - install.sh
        - render.yaml



