# Generated by Django 5.1.6 on 2025-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HRReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("icazəli", "İcazəli"), ("icazəsiz", "İcazəsiz")],
                        max_length=100,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
